import { Itinerario, Tappa } from './types';

// Itinerari "classici": strade-icona di ogni regione descritte da fonti
// pubbliche. I waypoint sono comuni e valichi reali con coordinate note;
// il tracciato di dettaglio su strada va rifinito da chi percorre il giro.
// Marcati origine 'classico': nessun dato spacciato per verificato in sella.

type TipoTappa = Tappa['tipo'];

function t(itinerario_id: string, righe: [number, string, TipoTappa, number, number, string | null][]): Tappa[] {
  return righe.map(([ordine, nome, tipo, lat, lng, note]) => ({
    id: `${itinerario_id}-${ordine}`, itinerario_id, ordine, nome, tipo, lat, lng,
    note: note ?? undefined,
  }));
}

export const ITINERARI_CLASSICI: Itinerario[] = [
  {
    id: 'tos-chianti',
    slug: 'chianti-firenze-siena',
    titolo: 'Strada del Chianti',
    sottotitolo: 'La Chiantigiana tra Firenze e Siena',
    descrizione: 'La SR222 Chiantigiana e\' la cartolina della Toscana in moto: saliscendi continui tra vigneti e oliveti, curve dolci e ben disegnate, borghi come Greve, Panzano, Castellina e Radda uno dietro l\'altro. Asfalto generalmente buono, traffico contenuto fuori stagione. Si presta a soste lunghe tra cantine e pievi. Primavera e autunno danno i colori migliori.',
    zona: 'Chianti (FI-SI)',
    regioni: ['toscana'],
    origine: 'classico',
    km: 70,
    durata_ore: 3,
    difficolta: 'facile',
    periodo_ideale: 'Aprile-Giugno e Settembre-Ottobre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[43.7696, 11.2558], [43.5836, 11.3157], [43.5471, 11.3162], [43.4699, 11.2837], [43.3188, 11.3308]],
    tappe: t('tos-chianti', [
      [1, 'Firenze', 'partenza', 43.7696, 11.2558, 'Si imbocca la SR222 da sud citta\''],
      [2, 'Greve in Chianti', 'sosta', 43.5836, 11.3157, 'Piazza Matteotti, cuore del Chianti'],
      [3, 'Panzano', 'panorama', 43.5471, 11.3162, 'Vista sulle colline'],
      [4, 'Castellina in Chianti', 'sosta', 43.4699, 11.2837, null],
      [5, 'Siena', 'arrivo', 43.3188, 11.3308, 'La citta\' del Palio'],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'tos-orcia',
    slug: 'val-d-orcia-amiata',
    titolo: 'Val d\'Orcia e Monte Amiata',
    sottotitolo: 'Colline UNESCO e la salita all\'Amiata',
    descrizione: 'Uno dei paesaggi piu\' fotografati d\'Italia: le crete della Val d\'Orcia tra Pienza, San Quirico e Montalcino, poi la strada tutta curve che sale al Monte Amiata passando per l\'Abbazia di Sant\'Antimo. Tratti piu\' tecnici rispetto alle colline del Chianti, panorami amplissimi. Sosta classica alle terme di Bagno Vignoni.',
    zona: 'Val d\'Orcia (SI)',
    regioni: ['toscana'],
    origine: 'classico',
    km: 110,
    durata_ore: 4,
    difficolta: 'medio',
    periodo_ideale: 'Aprile-Ottobre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[43.0576, 11.4894], [43.0167, 11.5167], [43.0289, 11.6181], [43.0786, 11.6789], [42.8886, 11.6206]],
    tappe: t('tos-orcia', [
      [1, 'Montalcino', 'partenza', 43.0576, 11.4894, 'Terra del Brunello'],
      [2, 'Abbazia di Sant\'Antimo', 'panorama', 43.0167, 11.5167, 'Strada tutta curve verso l\'abbazia'],
      [3, 'Bagno Vignoni', 'sosta', 43.0289, 11.6181, 'Terme nella piazza-vasca'],
      [4, 'Pienza', 'sosta', 43.0786, 11.6789, 'Borgo rinascimentale, pecorino'],
      [5, 'Monte Amiata', 'arrivo', 42.8886, 11.6206, 'Salita panoramica al vulcano spento'],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'tos-futa',
    slug: 'passo-della-futa-raticosa',
    titolo: 'Passo della Futa e Raticosa',
    sottotitolo: 'I due passi-icona dell\'Appennino',
    descrizione: 'La SS65 della Futa collega Firenze a Bologna ed e\' uno dei valichi piu\' frequentati dai motociclisti del centro Italia: curve ampie, buon grip, ritrovo storico al valico. Si abbina alla Raticosa, piu\' stretta e tecnica. Nei weekend primaverili il traffico aumenta: meglio partire presto.',
    zona: 'Appennino tosco-emiliano',
    regioni: ['toscana', 'emilia-romagna'],
    origine: 'classico',
    km: 60,
    durata_ore: 2,
    difficolta: 'medio',
    periodo_ideale: 'Maggio-Ottobre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[43.9622, 11.3247], [44.0731, 11.3017], [44.1136, 11.3361], [44.1242, 11.3506]],
    tappe: t('tos-futa', [
      [1, 'San Piero a Sieve', 'partenza', 43.9622, 11.3247, 'Imbocco SS65 da sud'],
      [2, 'Passo della Futa', 'panorama', 44.0731, 11.3017, 'Valico a 903 m, punto di ritrovo'],
      [3, 'Passo della Raticosa', 'panorama', 44.1136, 11.3361, 'Piu\' stretto e tecnico, 968 m'],
      [4, 'Pietramala', 'arrivo', 44.1242, 11.3506, null],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'tos-muraglione',
    slug: 'passo-del-muraglione',
    titolo: 'Passo del Muraglione',
    sottotitolo: 'La SS67 tra Toscana e Romagna',
    descrizione: 'La SS67 tra Pontassieve e Forli\' sale al Passo del Muraglione, piu\' tecnico della Futa: curve ravvicinate, variazioni di raggio, traffico turistico nelle belle giornate. Il valico, riconoscibile per il muro che lo protegge dal vento, e\' un ritrovo storico per motociclisti.',
    zona: 'Appennino (FI-FC)',
    regioni: ['toscana', 'emilia-romagna'],
    origine: 'classico',
    km: 40,
    durata_ore: 2,
    difficolta: 'medio',
    periodo_ideale: 'Maggio-Giugno e Settembre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[43.7758, 11.4392], [43.9217, 11.6217], [43.9544, 11.6889], [44.0589, 11.8444]],
    tappe: t('tos-muraglione', [
      [1, 'Pontassieve', 'partenza', 43.7758, 11.4392, null],
      [2, 'San Godenzo', 'sosta', 43.9217, 11.6217, null],
      [3, 'Passo del Muraglione', 'panorama', 43.9544, 11.6889, 'Valico a 907 m'],
      [4, 'Rocca San Casciano', 'arrivo', 44.0589, 11.8444, null],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'tos-maremma',
    slug: 'maremma-argentario',
    titolo: 'Maremma e Argentario',
    sottotitolo: 'Colline selvagge e il giro del promontorio',
    descrizione: 'La Maremma e\' la Toscana piu\' selvaggia: borghi come Pitigliano, Sorano e Manciano, le terme di Saturnia, poi la discesa al mare e il periplo del promontorio dell\'Argentario con le curve a strapiombo su Porto Santo Stefano e Porto Ercole. Strade meno affollate dell\'interno senese, paesaggi che cambiano in fretta.',
    zona: 'Maremma (GR)',
    regioni: ['toscana'],
    origine: 'classico',
    km: 130,
    durata_ore: 5,
    difficolta: 'medio',
    periodo_ideale: 'Marzo-Novembre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[42.6353, 11.6694], [42.73, 11.5044], [42.5878, 11.5169], [42.4406, 11.2206], [42.435, 11.117]],
    tappe: t('tos-maremma', [
      [1, 'Pitigliano', 'partenza', 42.6353, 11.6694, 'Il paese del tufo'],
      [2, 'Saturnia', 'sosta', 42.73, 11.5044, 'Cascate del Mulino'],
      [3, 'Manciano', 'sosta', 42.5878, 11.5169, null],
      [4, 'Orbetello', 'panorama', 42.4406, 11.2206, 'La laguna e la diga'],
      [5, 'Monte Argentario', 'arrivo', 42.435, 11.117, 'Periplo del promontorio'],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'umb-castelluccio',
    slug: 'castelluccio-piani-grandi',
    titolo: 'Castelluccio e i Piani Grandi',
    sottotitolo: 'La fioritura e l\'altopiano dei Sibillini',
    descrizione: 'La salita a Castelluccio di Norcia attraverso i Piani Grandi e\' uno dei percorsi piu\' spettacolari dell\'Appennino: lunghi rettilinei sull\'altopiano, tornanti in salita, l\'anfiteatro dei Monti Sibillini intorno. Tra fine maggio e luglio la fioritura della lenticchia colora la piana. Quota alta: attenzione al meteo e alle chiusure invernali.',
    zona: 'Monti Sibillini (PG)',
    regioni: ['umbria', 'marche'],
    origine: 'classico',
    km: 90,
    durata_ore: 4,
    difficolta: 'medio',
    periodo_ideale: 'Giugno-Settembre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[42.7928, 13.0961], [42.7544, 13.1733], [42.8167, 13.2], [42.8294, 13.2103]],
    tappe: t('umb-castelluccio', [
      [1, 'Norcia', 'partenza', 42.7928, 13.0961, 'Citta\' di San Benedetto'],
      [2, 'Forca Canapine', 'panorama', 42.7544, 13.1733, null],
      [3, 'Piani Grandi', 'panorama', 42.8167, 13.2, 'L\'altopiano della fioritura'],
      [4, 'Castelluccio di Norcia', 'arrivo', 42.8294, 13.2103, 'Borgo a 1452 m'],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'umb-valnerina',
    slug: 'valnerina-cascata-marmore',
    titolo: 'Valnerina e Cascata delle Marmore',
    sottotitolo: 'Il Nera tra gole e abbazie',
    descrizione: 'La Valnerina segue il corso del fiume Nera tra gole strette, abbazie e borghi appesi alla roccia: dalla Cascata delle Marmore si risale verso Ferentillo, Scheggino e Sant\'Anatolia, fino a Norcia. Strada scorrevole con tratti tecnici nelle gole, sempre in mezzo al verde.',
    zona: 'Valnerina (TR-PG)',
    regioni: ['umbria'],
    origine: 'classico',
    km: 80,
    durata_ore: 3,
    difficolta: 'facile',
    periodo_ideale: 'Marzo-Novembre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[42.5511, 12.715], [42.6258, 12.7672], [42.7106, 12.8311], [42.7928, 13.0961]],
    tappe: t('umb-valnerina', [
      [1, 'Cascata delle Marmore', 'partenza', 42.5511, 12.715, 'La cascata piu\' alta d\'Europa'],
      [2, 'Ferentillo', 'sosta', 42.6258, 12.7672, null],
      [3, 'Scheggino', 'sosta', 42.7106, 12.8311, null],
      [4, 'Norcia', 'arrivo', 42.7928, 13.0961, null],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'umb-sagrantino',
    slug: 'strada-del-sagrantino',
    titolo: 'Strada del Sagrantino',
    sottotitolo: 'Colline di vino tra Montefalco e Spello',
    descrizione: 'Un anello dolce tra le colline del Sagrantino: Montefalco la ringhiera dell\'Umbria per i panorami, Bevagna e Spello tra i borghi piu\' belli d\'Italia. Curve morbide, saliscendi, vigneti a perdita d\'occhio. Giro corto e rilassante, perfetto da abbinare a una sosta enogastronomica.',
    zona: 'Colline di Foligno (PG)',
    regioni: ['umbria'],
    origine: 'classico',
    km: 55,
    durata_ore: 2,
    difficolta: 'facile',
    periodo_ideale: 'Tutto l\'anno',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[42.8917, 12.6536], [42.9333, 12.6097], [42.9919, 12.6717]],
    tappe: t('umb-sagrantino', [
      [1, 'Montefalco', 'partenza', 42.8917, 12.6536, 'La ringhiera dell\'Umbria'],
      [2, 'Bevagna', 'sosta', 42.9333, 12.6097, null],
      [3, 'Spello', 'arrivo', 42.9919, 12.6717, 'Vicoli fioriti'],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'umb-trasimeno',
    slug: 'anello-del-trasimeno',
    titolo: 'Anello del Trasimeno',
    sottotitolo: 'Il lago, i borghi e i colli sopra Tuoro',
    descrizione: 'Il giro del lago Trasimeno alterna lungolago e salite panoramiche: da Magione e Passignano si sale verso Castel Rigone e i colli sopra Tuoro, con vista aperta sul lago e le sue isole. Strade tranquille, tornanti nella parte alta, clima mite quasi tutto l\'anno.',
    zona: 'Lago Trasimeno (PG)',
    regioni: ['umbria'],
    origine: 'classico',
    km: 75,
    durata_ore: 3,
    difficolta: 'facile',
    periodo_ideale: 'Marzo-Novembre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[43.1428, 12.205], [43.185, 12.1369], [43.205, 12.1844], [43.2069, 12.0772]],
    tappe: t('umb-trasimeno', [
      [1, 'Magione', 'partenza', 43.1428, 12.205, null],
      [2, 'Passignano sul Trasimeno', 'sosta', 43.185, 12.1369, 'Lungolago'],
      [3, 'Castel Rigone', 'panorama', 43.205, 12.1844, 'Vista sul lago'],
      [4, 'Tuoro sul Trasimeno', 'arrivo', 43.2069, 12.0772, 'Campo della battaglia di Annibale'],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'umb-spoleto',
    slug: 'spoleto-monteluco',
    titolo: 'Spoleto e Monteluco',
    sottotitolo: 'Tornanti nel bosco sacro sopra Spoleto',
    descrizione: 'Da Spoleto, citta\' del Festival dei Due Mondi difesa dal Ponte delle Torri, si sale tra i tornanti al bosco sacro di Monteluco: faggi e lecci secolari, eremi, vista sulla valle. Salita breve ma tecnica, pochissimo traffico, da chiudere con i sapori dello spoletino.',
    zona: 'Spoletino (PG)',
    regioni: ['umbria'],
    origine: 'classico',
    km: 50,
    durata_ore: 2,
    difficolta: 'medio',
    periodo_ideale: 'Aprile-Ottobre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[42.7402, 12.7386], [42.7256, 12.76], [42.73, 12.745]],
    tappe: t('umb-spoleto', [
      [1, 'Spoleto', 'partenza', 42.7402, 12.7386, 'Il Ponte delle Torri'],
      [2, 'Monteluco', 'panorama', 42.7256, 12.76, 'Il bosco sacro'],
      [3, 'San Pietro', 'arrivo', 42.73, 12.745, null],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'mar-furlo',
    slug: 'gola-del-furlo',
    titolo: 'Gola del Furlo',
    sottotitolo: 'La Flaminia che taglia la roccia',
    descrizione: 'La Gola del Furlo e\' uno dei passaggi piu\' scenografici delle Marche: la vecchia Flaminia (SS3) si infila in una stretta gola scavata dal fiume Candigliano, tra pareti a strapiombo e una galleria di epoca romana. Tratto breve ma indimenticabile, da abbinare ai borghi dell\'entroterra pesarese.',
    zona: 'Gola del Furlo (PU)',
    regioni: ['marche'],
    origine: 'classico',
    km: 50,
    durata_ore: 2,
    difficolta: 'facile',
    periodo_ideale: 'Marzo-Novembre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[43.6175, 12.6694], [43.6469, 12.7144], [43.6781, 12.6483]],
    tappe: t('mar-furlo', [
      [1, 'Acqualagna', 'partenza', 43.6175, 12.6694, 'Capitale del tartufo'],
      [2, 'Gola del Furlo', 'panorama', 43.6469, 12.7144, 'La galleria romana nella roccia'],
      [3, 'Fermignano', 'arrivo', 43.6781, 12.6483, null],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'mar-frasassi',
    slug: 'frasassi-valle-esino',
    titolo: 'Frasassi e la Valle dell\'Esino',
    sottotitolo: 'Gole, grotte e l\'eremo nella roccia',
    descrizione: 'La Valle dell\'Esino sale verso le Grotte di Frasassi e la Gola della Rossa, tra le aree calcaree piu\' spettacolari dell\'Appennino. Curve nelle gole, l\'eremo di Santa Maria infra Saxa incastonato nella parete, borghi come Genga e Arcevia. Strada varia e mai banale.',
    zona: 'Gola della Rossa (AN)',
    regioni: ['marche'],
    origine: 'classico',
    km: 70,
    durata_ore: 3,
    difficolta: 'medio',
    periodo_ideale: 'Marzo-Novembre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[43.3358, 12.905], [43.4017, 12.9656], [43.4283, 12.9444], [43.5006, 12.9408]],
    tappe: t('mar-frasassi', [
      [1, 'Fabriano', 'partenza', 43.3358, 12.905, 'Citta\' della carta'],
      [2, 'Grotte di Frasassi', 'sosta', 43.4017, 12.9656, 'Le grotte e l\'eremo'],
      [3, 'Genga', 'panorama', 43.4283, 12.9444, null],
      [4, 'Arcevia', 'arrivo', 43.5006, 12.9408, null],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'mar-conero',
    slug: 'riviera-del-conero',
    titolo: 'Riviera del Conero',
    sottotitolo: 'Il promontorio a picco sull\'Adriatico',
    descrizione: 'Il Monte Conero e\' l\'unico promontorio dell\'Adriatico tra Trieste e il Gargano: strade panoramiche tra la macchia mediterranea, scorci sulle spiagge bianche di Sirolo e Numana, salita al belvedere del Conero. Curve dolci e mare sempre in vista, ideale fuori dai mesi piu\' affollati.',
    zona: 'Monte Conero (AN)',
    regioni: ['marche'],
    origine: 'classico',
    km: 45,
    durata_ore: 2,
    difficolta: 'facile',
    periodo_ideale: 'Aprile-Giugno e Settembre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[43.6158, 13.5189], [43.5247, 13.6189], [43.5106, 13.6231], [43.555, 13.6017]],
    tappe: t('mar-conero', [
      [1, 'Ancona', 'partenza', 43.6158, 13.5189, null],
      [2, 'Sirolo', 'panorama', 43.5247, 13.6189, 'Spiagge bianche del Conero'],
      [3, 'Numana', 'sosta', 43.5106, 13.6231, null],
      [4, 'Monte Conero', 'arrivo', 43.555, 13.6017, 'Belvedere a picco sul mare'],
    ]),
    avvisi: [],
    pro_extra: null,
  },
  {
    id: 'mar-sanbartolo',
    slug: 'san-bartolo-gabicce',
    titolo: 'Parco del San Bartolo',
    sottotitolo: 'Da Gabicce a Pesaro sul mare',
    descrizione: 'La strada panoramica del Parco del San Bartolo corre sul crinale a picco sull\'Adriatico tra Gabicce Monte e Pesaro: tornanti stretti, vista continua sul mare, borghi come Casteldimezzo e Fiorenzuola di Focara. Breve ma intensa, una delle piu\' fotografate dell\'alta costa marchigiana.',
    zona: 'San Bartolo (PU)',
    regioni: ['marche'],
    origine: 'classico',
    km: 35,
    durata_ore: 2,
    difficolta: 'medio',
    periodo_ideale: 'Marzo-Novembre',
    gpx_url: null,
    is_premium: false,
    cover_url: null,
    strada: null,
    strada_fonte: null,
    tracciato: [[43.9683, 12.76], [43.945, 12.7889], [43.9347, 12.8086], [43.9102, 12.9133]],
    tappe: t('mar-sanbartolo', [
      [1, 'Gabicce Monte', 'partenza', 43.9683, 12.76, 'Belvedere sulla riviera'],
      [2, 'Casteldimezzo', 'panorama', 43.945, 12.7889, null],
      [3, 'Fiorenzuola di Focara', 'sosta', 43.9347, 12.8086, null],
      [4, 'Pesaro', 'arrivo', 43.9102, 12.9133, 'Il lungomare e la Sfera di Pomodoro'],
    ]),
    avvisi: [],
    pro_extra: null,
  },
];
